name: namer_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  bot_toast: ^4.1.3
  dio: ^5.3.3
  english_words: ^4.0.0
  firebase_auth: ^4.13.0
  firebase_core: ^2.12.0
  firebase_messaging: ^14.7.4
  flutter:
    sdk: flutter
  flutter_application_1: ^0.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_map: ^6.0.1
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.1.6
  mockito: ^5.4.3
  provider: ^6.0.0

dependency_overrides:
  firebase_core_platform_interface: 5.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/background1.png
    - assets/background2.png
    - assets/background3.png
    - assets/background4.png
    - assets/annonce.png